Sun Dec 27 00:00:01 CST 2015 --- Clear Log OK

lxw_IOError: 	2015-12-27-09:10:01
[Errno 2] No such file or directory: './Intermedia/http:__www.isra.org.cn_news_index.htm'
lxw_IOError: 	2015-12-27-09:10:05
[Errno 2] No such file or directory: './Intermedia/https:__www.powerdns.com_news_news-archive.html'
lxw_IOError: 	2015-12-27-09:10:22
[Errno 2] No such file or directory: './Intermedia/http:__www.dotasia.org_index.html'
EMAIL SENDING: 	2015-12-27-09:10:22

EMAIL SENDING SUCCESS: 	2015-12-27-09:10:35

EMAIL SENDING: 	2015-12-27-09:10:35

EMAIL SENDING SUCCESS: 	2015-12-27-09:10:41

Monitor Finished.   Monitor Time: 2015-12-27-09:10:41.   Time Cost: 0'39"
------------------------------------------------------------------------------

------------------------------------------------------------------------------
lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:01
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__apac.cn_secgames_'

lxw_IOError: 	2015-12-29-09:10:02
[Errno 2] No such file or directory: './Intermedia/http:__www.isra.org.cn_news_index.htm'
lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:02
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.wooyun.org_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:02
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.cert.org.cn_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:02
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.cnvd.org.cn_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:02
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__loudong.360.cn_vul_list'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:02
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/https:__www.monic.mo_monic_faces_index'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:02
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.aptld.org_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:02
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__blog.dnspod.cn_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:03
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.sgnic.sg_'

lxw_IOError: 	2015-12-29-09:10:03
[Errno 2] No such file or directory: './Intermedia/https:__www.powerdns.com_news_news-archive.html'
lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:03
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.isc.org.cn_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:03
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/https:__www.dns-oarc.net_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:03
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.ietf.org_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:03
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/https:__www.icann.org_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:03
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.us-cert.gov_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:03
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/https:__www.hkdnr.hk_?lang=cn'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:03
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.apnic.net_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:04
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/https:__www.opendns.com_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:04
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.ripe.net_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:05
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.afilias.info_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:05
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.verisigninc.com_zh_CN_internet-technology-news_verisign-press-releases_archives_index.xhtml'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:05
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__pir.org_news-events_for-press_press-releases_'

Information: URL recovery. lxw_KeyError: http://www.twnic.tw/index4.php	2015-12-29-09:10:05

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:05
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.twnic.tw_index4.php'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:05
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.afrinic.net_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:07
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.denic.de_en_homepage.html'

lxw_IOError: 	2015-12-29-09:10:08
[Errno 2] No such file or directory: './Intermedia/http:__www.dotasia.org_index.html'
lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:09
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.nsfocus.com_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:10
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.nominet.org.uk_news_press-releases'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:11
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.afnic.fr_en_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:11
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.isc.org_downloads_software-support-policy_security-advisory_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:11
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.isc.org_downloads_bind_'

lxw_IOERROR Occurred(File not found, url revives now.): 	2015-12-29-09:10:12
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 694, in diff2Str
    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './Intermedia/http:__www.cira.ca_news_news-releases_'

EMAIL SENDING: 	2015-12-29-09:10:12

EMAIL SENDING SUCCESS: 	2015-12-29-09:10:18

Monitor Finished.   Monitor Time: 2015-12-29-09:10:18.   Time Cost: 0'16"
------------------------------------------------------------------------------

------------------------------------------------------------------------------
lxw_IOError: 	2015-12-30-09:10:02
[Errno 2] No such file or directory: './Intermedia/http:__www.isra.org.cn_news_index.htm'
lxw_IOError: 	2015-12-30-09:10:06
[Errno 2] No such file or directory: './Intermedia/https:__www.powerdns.com_news_news-archive.html'
lxw_IOError: 	2015-12-30-09:10:08
[Errno 2] No such file or directory: './Intermedia/http:__www.dotasia.org_index.html'
EMAIL SENDING: 	2015-12-30-09:10:12

EMAIL SENDING SUCCESS: 	2015-12-30-09:10:27

Monitor Finished.   Monitor Time: 2015-12-30-09:10:27.   Time Cost: 0'25"
------------------------------------------------------------------------------

------------------------------------------------------------------------------
